### PR TITLE
Updates to GSG index and MongoDB GSG

### PR DESCRIPTION
**Pull request by zcorleissen**

### CODE REVIEW

**Comment by SethSanchez** [comment]
Hey Zach!

Thanks for this, very much appreciated! The only comment I have before merging is that our default versions have changed, and are now `2.4.14`, `2.6.11`, and `3.0.7`. I'd also really like to keep the `please don't hesitate` on the last lines of each page, when contacting support.

Thanks!

**Comment by zcorleissen** [comment]
Hi Seth,

Thanks for the feedback! The version differences aren't yet reflected in the GUI--maybe the better solution is simply to stick with major release numbers as the docs do now. (2.4, 2.6, 3.0, etc.)

Normally, docs best practices are to focus on user actions, e.g. "contact support". Can you say more about why you'd like to keep the current language?

**Comment by SethSanchez** [comment]
The versioning makes sense, and it means less maintenance. We might say something like "the latest of each major version".

As for the verbiage, it matches the language we use in our support communications, so we were just keeping things consistent with people that are familiar with our support, or might interact with us.

**Comment by zcorleissen** [comment]
I like it. How about "the latest version of 2.4, 2.6", etc.?

I hear what you're saying. Let me run the differences in language past our editor and get her input.

**Comment by SethSanchez** [comment]
Sounds good on both counts.

**Comment by heydonovan** [comment]
I'm liking the updates to the "Getting Started with MongoDB" page (it mirrors the steps in the GUI). On "Step 2", number 2 and number 3 need to switch places, as the "Zone" drop-down comes before the "Plan" drop-down menu.

Thoughts on changing "Create an instance" to "Create Instance", to further mirror the GUI? Why are some versions of MongoDB denoted with a `v` before it? `v3.0` vs `3.0`? Also I noticed the e-mail link to the support team is `support%40objectrocket.com`, but I'm not sure if that was already there.

**Comment by zcorleissen** [comment]
@SethSanchez: From the devdoc editor:

"If you have any issues or just need guidance, contact our `support team <mailto:support@objectrocket.com>`_."

**Comment by zcorleissen** [comment]
@heydonovan: Good catch on zone/plan order. The Redis and MongoDB app page had the steps in a different order; I'm happy to see the update!

I think it's OK for descriptive text to differ from the GUI where exact mirroring might be confusing. In this case, "create an instance" seems more helpful when describing the function "create instance".

Good catch on inconsistent use of versioning conventions. I'll fix them.

Interesting note on the email link. I wonder if Sphinx builds `mailto:` links with the substitution. We should verify that the link works, preferably in a test environment (is there one?) but definitely after pushing to master.

**Comment by evanfreed** [comment]
Merged suggestions from @heydonovan into the documentation/zcorleissen-redis-gsg-review branch.  Pull request for branch here #76 .

**Pull request closed without merging**
