### PR TITLE
Add ORD to ServiceNet list.

### PR DESCRIPTION
**Pull request by evanfreed**
Solves #91

### CODE REVIEW

**Comment by evanfreed** [comment]
Threw in the fix for #92 also.

**Comment by SethSanchez** [comment]
I'd only change:

```
2.1+ use lowercase
```
to
```
2.1+ uses lowercase
```

but I'll also accept no as an answer and merge it anyway

**Comment by evanfreed** [comment]
Fixed

**Comment by jtharpla** [comment]
:+1: merge away, thanks dude!

**Pull request merged**
