### PR TITLE
Incorporating feedback to GSGs

### PR DESCRIPTION
**Pull request by zcorleissen**
I don't have sufficient admin privileges to build on #76, so please forgive the redundancy.

### CODE REVIEW

**Comment by evanfreed** [comment]
Since there's been a lot of redundancy in the pull requests can we try to get #76 merged and then rebase any other changes you have here off of that? Thanks for the input so far!

**Comment by zcorleissen** [comment]
Sure thing! I'll save my updates to Elasticsearch for post-merge.

**Comment by evanfreed** [comment]
@SethSanchez Does it look like we've merged most of the edits on the GS pages? I combined most of the redundant pull requests into this one. Is there anything else we should add before merging this?

**Comment by SethSanchez** [comment]
Ah, I was looking over #76. I'll look over this tonight and we can have it merged tomorrow if things look good. I just want to build it locally to make sure things look the way we expect.

**Comment by zcorleissen** [comment]
@evanfreed @SethSanchez I have similar edits to the Elasticsearch GSG page. Do we want to incorporate those into this PR or wait until after the merge?

**Comment by SethSanchez** [comment]
I'd chuck em in here @zcorleissen, we might as well merge em in too. Saves some time.

**Comment by zcorleissen** [comment]
@SethSanchez OK. There will be a lot of questions, specifically about Kibana versioning, but we can at least get started.

**Comment by evanfreed** [comment]
My comment ^^ was suppose to be for #76... too many tabs open sorry.

**Comment by SethSanchez** [comment]
Gah, ok. So @zcorleissen, let me review #76. @evanfreed We're working out of which PR going forward, this or #76? Is #76 needed before this one?

**Comment by evanfreed** [comment]
Yes lets get #76 reviewed and merged and then rebase this one.

**Comment by zcorleissen** [comment]
@SethSanchez Heh, OK, let me revert that last commit.

**Comment by zcorleissen** [comment]
@SethSanchez @evanfreed OK, good to go.

**Comment by SethSanchez** [comment]
Ok, #76 merged. You guys want to rebase?

**Comment by zcorleissen** [comment]
Yes, let's do it. @evanfreed or @SethSanchez, want to do the honors?

**Pull request closed without merging**
