### PR TITLE
Update getting_started.rst

### PR DESCRIPTION
**Pull request by TrevorWinters**
Made updates to accommodate Redis and better align with the current process.

### CODE REVIEW

**Comment by TrevorWinters** [comment]
@TheDodd Who handles pull requests for the Document repo?  This puppy needs some love.  She hasn't been fed in 13 days.  Thanks for setting me straight.

**Comment by TrevorWinters** [comment]
@keithhigbee Would you please assist in getting this pull request inspected and rolled?  The current "Getting Started" documentation speaks to MongoDB and makes no mention of Redis.  Additionally, even for MongoDB it isn't accurate.

**Comment by TheDodd** [comment]
Looks like this needs to be rebased. Are these changes still needed, @TrevorWinters??

**Comment by SethSanchez** [comment]
Completed in my PR, and Trevor no longer works here.

**Pull request closed without merging**
